// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/image": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改自己上传的图片信息(仅标题,简介和标签允许修改,其他均以数据库已有信息为准)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "修改图片信息",
                "parameters": [
                    {
                        "description": "图片信息",
                        "name": "image",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Image"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "图片信息更新成功，返回更新后的图片信息",
                        "schema": {
                            "$ref": "#/definitions/model.Image"
                        }
                    },
                    "400": {
                        "description": "请求数据异常",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未授权，用户未登录或会话失效",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建图片对象,需要先调用 /image/file [POST] 接口,获取到图片对象(包括图片id,作者用户名以及图片各个大小的地址),然后将其他元数据补充入此对象,再请求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "创建图片元信息",
                "parameters": [
                    {
                        "description": "图片对象,在/image/file [POST] 接口的返回值上补充元数据所得",
                        "name": "image",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Image"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "图片对象",
                        "schema": {
                            "$ref": "#/definitions/model.Image"
                        }
                    },
                    "400": {
                        "description": "请求数据异常",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未授权，用户未登录或会话失效",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/image/file": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传图片文件，返回图片对象(包括图片id,作者用户名和地址).",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "上传图片文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "图片上传成功，返回图片对象",
                        "schema": {
                            "$ref": "#/definitions/model.Image"
                        }
                    },
                    "401": {
                        "description": "未授权，用户未登录或会话失效",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/image/from/{username}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询指定用户名上传的所有图片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "获取指定用户上传的所有图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回指定用户上传的所有图片信息",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Image"
                            }
                        }
                    },
                    "400": {
                        "description": "用户未上传图片或用户不存在,注意这个情况有时候不是错误,只是异常,需要进行处理",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/image/newest": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取最新的9张图片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "获取最新的9张图片",
                "responses": {
                    "200": {
                        "description": "返回最新的9张图片信息",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Image"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/image/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询图片，进行标签匹配和标题模糊匹配",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "查询图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "查询内容",
                        "name": "search",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回符合查询条件的图片信息",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Image"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/image/{imageID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据提供的图片ID，查找并返回该图片对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "获取指定ID的图片对象",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图片ID",
                        "name": "imageID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "图片对象",
                        "schema": {
                            "$ref": "#/definitions/model.Image"
                        }
                    },
                    "400": {
                        "description": "请求错误，图片ID无效",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未授权，用户未登录或会话失效",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除自己上传的指定ID的图片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "删除指定ID的图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图片ID",
                        "name": "imageID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "图片删除成功，无返回内容"
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未授权，用户未登录或会话失效",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "未找到图片，图片ID不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "允许已登录的用户更新自己的信息，包括密码。如果没有提供密码，密码保持不变。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "用户信息更新成功，无返回内容"
                    },
                    "401": {
                        "description": "未授权错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "禁止操作，尝试修改非自己的信息",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/avatar": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传用户自己的头像文件,后续需要再请求一次/user [put]来更新用户信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "user"
                ],
                "summary": "上传用户头像",
                "parameters": [
                    {
                        "type": "file",
                        "description": "用户上传的头像文件",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "返回头像存储路径",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "用户未授权",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "用户通过用户名和密码登录，成功后返回 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录信息(只需要username和password)",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JWT Token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "用户进行注册，成功后返回 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户注册信息(只需要username和password)",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "JWT Token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "用户名已存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/star": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询用户自己的所有收藏信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户的收藏信息",
                "responses": {
                    "200": {
                        "description": "返回用户的所有收藏记录",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Star"
                            }
                        }
                    },
                    "401": {
                        "description": "未授权，用户未登录或会话失效",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户收藏指定的图片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户收藏图片",
                "parameters": [
                    {
                        "description": "收藏信息,只需要图片ID",
                        "name": "star",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Star"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "图片收藏成功，无返回内容"
                    },
                    "400": {
                        "description": "请求错误，图片不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未授权，用户未登录或会话失效",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "取消自己收藏的图片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "取消用户的图片收藏",
                "parameters": [
                    {
                        "description": "收藏信息,只需要图片ID",
                        "name": "star",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Star"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "取消收藏成功，无返回内容"
                    },
                    "400": {
                        "description": "请求错误，收藏记录不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未授权，用户未登录或会话失效",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/{username}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据用户名获取用户详细信息(无密码)，需要JWT验证",
                "tags": [
                    "user"
                ],
                "summary": "获取指定用户名的用户对象(无密码)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户对象(无密码)",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "401": {
                        "description": "未授权错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Image": {
            "description": "图片",
            "type": "object",
            "properties": {
                "auth": {
                    "description": "图片作者用户名",
                    "type": "string",
                    "example": "test"
                },
                "bigURI": {
                    "description": "大图地址",
                    "type": "string",
                    "example": "assert/images/big_68c8d808-54f7-4cfc-94c9-015416033dc9.jpg"
                },
                "createAt": {
                    "description": "创建时间",
                    "type": "string",
                    "example": "2024-12-03T10:18:36.897966604+08:00"
                },
                "id": {
                    "description": "图片id(UUID)",
                    "type": "string",
                    "example": "68c8d808-54f7-4cfc-94c9-015416033dc9"
                },
                "intro": {
                    "description": "图片简介",
                    "type": "string"
                },
                "label": {
                    "description": "图片标签",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "like": {
                    "description": "收藏人数",
                    "type": "integer",
                    "example": 0
                },
                "midURI": {
                    "description": "中图地址",
                    "type": "string",
                    "example": "assert/images/med_68c8d808-54f7-4cfc-94c9-015416033dc9.jpg"
                },
                "title": {
                    "description": "图片标题",
                    "type": "string",
                    "example": "test"
                }
            }
        },
        "model.Star": {
            "description": "收藏信息",
            "type": "object",
            "properties": {
                "imageID": {
                    "description": "图片ID",
                    "type": "string",
                    "example": "68c8d808-54f7-4cfc-94c9-015416033dc9"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "test"
                }
            }
        },
        "model.User": {
            "description": "用户",
            "type": "object",
            "properties": {
                "avatarURI": {
                    "description": "头像地址",
                    "type": "string",
                    "example": "assert/avatars/d18b9c4b-8d7f-407f-a630-cf2596bd7511.jpg"
                },
                "intro": {
                    "description": "描述",
                    "type": "string",
                    "example": "我是test"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string",
                    "example": "test"
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "test"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8880",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "绘画交流平台",
	Description:      "绘画交流平台的后端API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
