basePath: /
definitions:
  model.User:
    description: 用户
    properties:
      avatarURI:
        description: 头像地址
        example: TODO
        type: string
      intro:
        description: 描述
        example: 我是test
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
      username:
        description: 用户名
        example: test
        type: string
    type: object
host: localhost:8880
info:
  contact: {}
  description: 绘画交流平台的后端API文档
  title: 绘画交流平台
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户通过用户名和密码登录，成功后返回 JWT Token
      parameters:
      - description: 用户登录信息(只需要username和password)
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - text/plain
      responses:
        "200":
          description: JWT Token
          schema:
            type: string
        "403":
          description: 用户名或密码错误
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      summary: 用户登录
      tags:
      - auth
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户进行注册，成功后返回 JWT Token
      parameters:
      - description: 用户注册信息(只需要username和password)
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - text/plain
      responses:
        "201":
          description: JWT Token
          schema:
            type: string
        "403":
          description: 用户名已存在
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      summary: 用户注册
      tags:
      - auth
securityDefinitions:
  jwt:
    in: header
    name: Bearer
    type: apiKey
swagger: "2.0"
