basePath: /
definitions:
  model.Image:
    description: 图片
    properties:
      auth:
        description: 图片作者用户名
        example: test
        type: string
      bigURI:
        description: 大图地址
        example: assert/images/big_68c8d808-54f7-4cfc-94c9-015416033dc9.jpg
        type: string
      createAt:
        description: 创建时间
        example: "2024-12-03T10:18:36.897966604+08:00"
        type: string
      id:
        description: 图片id(UUID)
        example: 68c8d808-54f7-4cfc-94c9-015416033dc9
        type: string
      intro:
        description: 图片简介
        type: string
      label:
        description: 图片标签
        items:
          type: string
        type: array
      like:
        description: 收藏人数
        example: 0
        type: integer
      mediumURI:
        description: 中图地址
        example: TODO
        type: string
      smallURI:
        description: 小图地址
        example: TODO
        type: string
      title:
        description: 图片标题
        example: test
        type: string
    type: object
  model.Star:
    description: 收藏信息
    properties:
      imageID:
        description: 图片ID
        example: 68c8d808-54f7-4cfc-94c9-015416033dc9
        type: string
      username:
        description: 用户名
        example: test
        type: string
    type: object
  model.User:
    description: 用户
    properties:
      avatarURI:
        description: 头像地址
        example: TODO
        type: string
      intro:
        description: 描述
        example: 我是test
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
      username:
        description: 用户名
        example: test
        type: string
    type: object
host: localhost:8880
info:
  contact: {}
  description: 绘画交流平台的后端API文档
  title: 绘画交流平台
  version: "1.0"
paths:
  /image:
    post:
      consumes:
      - application/json
      description: 创建图片对象,需要先调用 /image/file [POST] 接口,获取到图片对象(包括图片id,作者用户名以及图片各个大小的地址),然后将其他元数据补充入此对象,再请求
      parameters:
      - description: 图片对象,在/image/file [POST] 接口的返回值上补充元数据所得
        in: body
        name: image
        required: true
        schema:
          $ref: '#/definitions/model.Image'
      produces:
      - application/json
      responses:
        "201":
          description: 图片对象
          schema:
            $ref: '#/definitions/model.Image'
        "400":
          description: 请求数据异常
          schema:
            type: string
        "401":
          description: 未授权，用户未登录或会话失效
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 创建图片元信息
      tags:
      - image
    put:
      consumes:
      - application/json
      description: 修改自己上传的图片信息(仅标题,简介和标签允许修改,其他均以数据库已有信息为准)
      parameters:
      - description: 图片信息
        in: body
        name: image
        required: true
        schema:
          $ref: '#/definitions/model.Image'
      produces:
      - application/json
      responses:
        "201":
          description: 图片信息更新成功，返回更新后的图片信息
          schema:
            $ref: '#/definitions/model.Image'
        "400":
          description: 请求数据异常
          schema:
            type: string
        "401":
          description: 未授权，用户未登录或会话失效
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 修改图片信息
      tags:
      - image
  /image/{imageID}:
    delete:
      consumes:
      - application/json
      description: 删除自己上传的指定ID的图片
      parameters:
      - description: 图片ID
        in: path
        name: imageID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: 图片删除成功，无返回内容
        "400":
          description: 请求错误
          schema:
            type: string
        "401":
          description: 未授权，用户未登录或会话失效
          schema:
            type: string
        "404":
          description: 未找到图片，图片ID不存在
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 删除指定ID的图片
      tags:
      - image
    get:
      consumes:
      - application/json
      description: 根据提供的图片ID，查找并返回该图片对象
      parameters:
      - description: 图片ID
        in: path
        name: imageID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 图片对象
          schema:
            $ref: '#/definitions/model.Image'
        "400":
          description: 请求错误，图片ID无效
          schema:
            type: string
        "401":
          description: 未授权，用户未登录或会话失效
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 获取指定ID的图片对象
      tags:
      - image
  /image/file:
    post:
      consumes:
      - multipart/form-data
      description: 上传图片文件，返回图片对象(包括图片id,作者用户名和地址).
      parameters:
      - description: 图片文件
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: 图片上传成功，返回图片对象
          schema:
            $ref: '#/definitions/model.Image'
        "401":
          description: 未授权，用户未登录或会话失效
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 上传图片文件
      tags:
      - image
  /user:
    put:
      consumes:
      - application/json
      description: 允许已登录的用户更新自己的信息，包括密码。如果没有提供密码，密码保持不变。
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "204":
          description: 用户信息更新成功，无返回内容
        "401":
          description: 未授权错误
          schema:
            type: string
        "403":
          description: 禁止操作，尝试修改非自己的信息
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 更新用户信息
      tags:
      - user
  /user/{username}:
    get:
      description: 根据用户名获取用户详细信息(无密码)，需要JWT验证
      parameters:
      - description: 用户名
        in: path
        name: username
        required: true
        type: string
      responses:
        "200":
          description: 用户对象(无密码)
          schema:
            $ref: '#/definitions/model.User'
        "401":
          description: 未授权错误
          schema:
            type: string
        "404":
          description: 用户不存在
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 获取指定用户名的用户对象(无密码)
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户通过用户名和密码登录，成功后返回 JWT Token
      parameters:
      - description: 用户登录信息(只需要username和password)
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - text/plain
      responses:
        "200":
          description: JWT Token
          schema:
            type: string
        "403":
          description: 用户名或密码错误
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      summary: 用户登录
      tags:
      - auth
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户进行注册，成功后返回 JWT Token
      parameters:
      - description: 用户注册信息(只需要username和password)
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - text/plain
      responses:
        "201":
          description: JWT Token
          schema:
            type: string
        "403":
          description: 用户名已存在
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      summary: 用户注册
      tags:
      - auth
  /user/star:
    delete:
      consumes:
      - application/json
      description: 取消自己收藏的图片
      parameters:
      - description: 收藏信息,只需要图片ID
        in: body
        name: star
        required: true
        schema:
          $ref: '#/definitions/model.Star'
      produces:
      - application/json
      responses:
        "204":
          description: 取消收藏成功，无返回内容
        "400":
          description: 请求错误，收藏记录不存在
          schema:
            type: string
        "401":
          description: 未授权，用户未登录或会话失效
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 取消用户的图片收藏
      tags:
      - user
    get:
      consumes:
      - application/json
      description: 查询用户自己的所有收藏信息
      produces:
      - application/json
      responses:
        "200":
          description: 返回用户的所有收藏记录
          schema:
            items:
              $ref: '#/definitions/model.Star'
            type: array
        "401":
          description: 未授权，用户未登录或会话失效
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 获取用户的收藏信息
      tags:
      - user
    post:
      consumes:
      - application/json
      description: 用户收藏指定的图片
      parameters:
      - description: 收藏信息,只需要图片ID
        in: body
        name: star
        required: true
        schema:
          $ref: '#/definitions/model.Star'
      produces:
      - application/json
      responses:
        "204":
          description: 图片收藏成功，无返回内容
        "400":
          description: 请求错误，图片不存在
          schema:
            type: string
        "401":
          description: 未授权，用户未登录或会话失效
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 用户收藏图片
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
